#!/bin/bash

ZONE_ID="Z00951673I2OYCZYMUOPO"

echo "Deleting all running instance other than roboshop"


INSTANCES=$( aws ec2 describe-instances \
    --filters "Name=instance-state-name,Values=running" \
    --query "Reservations[].Instances[?Tags[?Key=='Name' && Value!='linux']].InstanceId" \
    --output text
)

echo ${#INSTANCES[@]}

# aws ec2 terminate-instances --instance-ids $INSTANCES

# echo "Deleted all running instance other than roboshop"

# echo "Deleting all R53 Records other than NS and SOA Types"

# aws route53 change-resource-record-sets \
#     --hosted-zone-id $ZONE_ID \
#     --change-batch "$(aws route53 list-resource-record-sets \
#         --hosted-zone-id $ZONE_ID \
#         --query "ResourceRecordSets[?Type!='NS' && Type!='SOA']" \
#         --output json | jq '{Changes: map({Action: "DELETE", ResourceRecordSet: .})}')"

# echo "Deleted all R53 Records other than NS and SOA Types"
