#!/bin/bash

INSTANCES=$( aws ec2 describe-instances \
    --filters "Name=instance-state-name,Values=running" \
    --query "Reservations[].Instances[?Tags[?Key=='Name' && Value!='linux']].InstanceId" \
    --output text
)

aws ec2 terminate-instances --instance-ids $INSTANCES
